// Code generated by go-validate. DO NOT EDIT.
package models

import (
	"fmt"
	"regexp"
)

type ValidationError struct {
	Field string
	Err   error
}

func (t User) Validate() ([]ValidationError, error) {
	var validErrs []ValidationError

	if len(t.ID) != 32 {
		validErrs = append(validErrs, ValidationError{
			Field: "ID",
			Err:   fmt.Errorf("wrong length: expected %d, got %d", 32, len(t.ID)),
		})
	}

	if t.Age < 18 {
		validErrs = append(validErrs, ValidationError{
			Field: "Age",
			Err:   fmt.Errorf("%d should be more than %d", t.Age, 18),
		})
	}

	if t.Age > 50 {
		validErrs = append(validErrs, ValidationError{
			Field: "Age",
			Err:   fmt.Errorf("%d should be less than %d", t.Age, 50),
		})
	}

	matched, err := regexp.MatchString("^\\w+@\\w+\\.\\w+$", t.Email)
	if err != nil {
		return validErrs, fmt.Errorf("wrong regexp")
	}
	if !matched {
		validErrs = append(validErrs, ValidationError{
			Field: "Email",
			Err:   fmt.Errorf("%s does not match regexp", t.Email),
		})
	}

	for i, _ := range t.Addresses {

		if len(t.Addresses[i]) != 250 {
			validErrs = append(validErrs, ValidationError{
				Field: "Addresses[i]",
				Err:   fmt.Errorf("wrong length: expected %d, got %d", 250, len(t.Addresses[i])),
			})
		}

	}

	return validErrs, nil
}
func (t App) Validate() ([]ValidationError, error) {
	var validErrs []ValidationError

	if len(t.Version) != 5 {
		validErrs = append(validErrs, ValidationError{
			Field: "Version",
			Err:   fmt.Errorf("wrong length: expected %d, got %d", 5, len(t.Version)),
		})
	}

	return validErrs, nil
}
func (t Response) Validate() ([]ValidationError, error) {
	var validErrs []ValidationError

	intVariants := []int{in, 200, 404, 500}
	isVariant := false
	for _, i := range intVariants {
		if t.Code == i {
			isVariant = true
			break
		}
	}
	if !isVariant {
		validErrs = append(validErrs, ValidationError{
			Field: "Code",
			Err:   fmt.Errorf("not allowed value %d", t.Code),
		})
	}

	return validErrs, nil
}
